/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SettingsPanel.java
 *
 * Created on Sep 20, 2008, 9:07:52 PM
 */

package com.varaneckas.hawkscope.gui;

/**
 *
 * @author spajus
 */
public class SettingsViewPanel extends javax.swing.JPanel {

    /** Creates new form SettingsPanel */
    public SettingsViewPanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        settingsTabbedPane = new javax.swing.JTabbedPane();
        generalPanel = new javax.swing.JPanel();
        showHiddenFIlesCheckBox = new javax.swing.JCheckBox();
        splitMenusLabel1 = new javax.swing.JLabel();
        splitMenusLabel2 = new javax.swing.JLabel();
        displayBehaviorLabel = new javax.swing.JLabel();
        splitMenusPageSizeTextField = new javax.swing.JFormattedTextField();
        automaticUpdatesLabel = new javax.swing.JLabel();
        automaticUpdatesCheckBox = new javax.swing.JCheckBox();
        startupLabel = new javax.swing.JLabel();
        runOnStartupCheckBox = new javax.swing.JCheckBox();
        applicationsPanel = new javax.swing.JPanel();
        foldersLabel = new javax.swing.JLabel();
        filesLabel = new javax.swing.JLabel();
        autodetectFileManagerCheckBox = new javax.swing.JCheckBox();
        openWithLabel = new javax.swing.JLabel();
        openWIthChoiceButton = new javax.swing.JButton();
        autodetectApplicationCheckBox = new javax.swing.JCheckBox();
        fileTypeApplicationScrollPane = new javax.swing.JScrollPane();
        fileTypeApplicationTable = new javax.swing.JTable();
        errorReportingPanel = new javax.swing.JPanel();
        networkPanel = new javax.swing.JPanel();
        proxySettingsLabel = new javax.swing.JLabel();
        serverLabel = new javax.swing.JLabel();
        serverTextField = new javax.swing.JFormattedTextField();
        portTextField = new javax.swing.JFormattedTextField();
        portLabel = new javax.swing.JLabel();
        authRequiredCheckBox = new javax.swing.JCheckBox();
        usernameLabel = new javax.swing.JLabel();
        usernameTextField = new javax.swing.JTextField();
        passwordLabel = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();
        useProxyCheckBox = new javax.swing.JCheckBox();
        buttonsPanel = new javax.swing.JPanel();
        closeButton = new javax.swing.JButton();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.PAGE_AXIS));

        showHiddenFIlesCheckBox.setText("Show hidden files");

        splitMenusLabel1.setText("Split long menus into pages with ");

        splitMenusLabel2.setText("items per page");

        displayBehaviorLabel.setFont(new java.awt.Font("DejaVu Sans", 1, 13)); // NOI18N
        displayBehaviorLabel.setText("Display behavior");

        splitMenusPageSizeTextField.setText("20");

        automaticUpdatesLabel.setFont(new java.awt.Font("DejaVu Sans", 1, 13)); // NOI18N
        automaticUpdatesLabel.setText("Automatic updates");

        automaticUpdatesCheckBox.setText("Look for new versions on startup");

        startupLabel.setFont(new java.awt.Font("DejaVu Sans", 1, 13)); // NOI18N
        startupLabel.setText("Startup");

        runOnStartupCheckBox.setText("Run Hawkscope on startup");

        javax.swing.GroupLayout generalPanelLayout = new javax.swing.GroupLayout(generalPanel);
        generalPanel.setLayout(generalPanelLayout);
        generalPanelLayout.setHorizontalGroup(
            generalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(generalPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(generalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(generalPanelLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(showHiddenFIlesCheckBox))
                    .addGroup(generalPanelLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(runOnStartupCheckBox))
                    .addComponent(startupLabel)
                    .addComponent(displayBehaviorLabel)
                    .addGroup(generalPanelLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(automaticUpdatesCheckBox))
                    .addGroup(generalPanelLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(splitMenusLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(splitMenusPageSizeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(splitMenusLabel2))
                    .addComponent(automaticUpdatesLabel))
                .addContainerGap(143, Short.MAX_VALUE))
        );
        generalPanelLayout.setVerticalGroup(
            generalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(generalPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(startupLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(runOnStartupCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(displayBehaviorLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(showHiddenFIlesCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(generalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(splitMenusLabel1)
                    .addComponent(splitMenusLabel2)
                    .addComponent(splitMenusPageSizeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(automaticUpdatesLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(automaticUpdatesCheckBox)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        settingsTabbedPane.addTab("General", generalPanel);

        foldersLabel.setFont(new java.awt.Font("DejaVu Sans", 1, 13)); // NOI18N
        foldersLabel.setText("Folders");

        filesLabel.setFont(new java.awt.Font("DejaVu Sans", 1, 13)); // NOI18N
        filesLabel.setText("Files");

        autodetectFileManagerCheckBox.setText("autodetect file manager");

        openWithLabel.setText("Open with");

        openWIthChoiceButton.setText("Choose...");

        autodetectApplicationCheckBox.setText("autodetect application");

        fileTypeApplicationTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Extension", "Open with"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        fileTypeApplicationScrollPane.setViewportView(fileTypeApplicationTable);
        fileTypeApplicationTable.getColumnModel().getColumn(0).setResizable(false);

        javax.swing.GroupLayout applicationsPanelLayout = new javax.swing.GroupLayout(applicationsPanel);
        applicationsPanel.setLayout(applicationsPanelLayout);
        applicationsPanelLayout.setHorizontalGroup(
            applicationsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(applicationsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(applicationsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(foldersLabel)
                    .addComponent(filesLabel)
                    .addGroup(applicationsPanelLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(applicationsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(applicationsPanelLayout.createSequentialGroup()
                                .addComponent(openWithLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(openWIthChoiceButton))
                            .addComponent(autodetectFileManagerCheckBox)))
                    .addGroup(applicationsPanelLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(applicationsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fileTypeApplicationScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 503, Short.MAX_VALUE)
                            .addComponent(autodetectApplicationCheckBox))))
                .addContainerGap())
        );
        applicationsPanelLayout.setVerticalGroup(
            applicationsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(applicationsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(foldersLabel)
                .addGap(1, 1, 1)
                .addComponent(autodetectFileManagerCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(applicationsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(openWithLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(openWIthChoiceButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(filesLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(autodetectApplicationCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fileTypeApplicationScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        settingsTabbedPane.addTab("Applications", applicationsPanel);

        javax.swing.GroupLayout errorReportingPanelLayout = new javax.swing.GroupLayout(errorReportingPanel);
        errorReportingPanel.setLayout(errorReportingPanelLayout);
        errorReportingPanelLayout.setHorizontalGroup(
            errorReportingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 539, Short.MAX_VALUE)
        );
        errorReportingPanelLayout.setVerticalGroup(
            errorReportingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 256, Short.MAX_VALUE)
        );

        settingsTabbedPane.addTab("Error Reporting", errorReportingPanel);

        proxySettingsLabel.setFont(new java.awt.Font("DejaVu Sans", 1, 13)); // NOI18N
        proxySettingsLabel.setText("Proxy settings");

        serverLabel.setText("Server");

        serverTextField.setText("172.0.0.1");

        portTextField.setText("8080");

        portLabel.setText("Port");

        authRequiredCheckBox.setText("Authentication required");

        usernameLabel.setText("Username");

        passwordLabel.setText("Password");

        useProxyCheckBox.setText("Use Proxy server");

        javax.swing.GroupLayout networkPanelLayout = new javax.swing.GroupLayout(networkPanel);
        networkPanel.setLayout(networkPanelLayout);
        networkPanelLayout.setHorizontalGroup(
            networkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(networkPanelLayout.createSequentialGroup()
                .addGroup(networkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(networkPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(proxySettingsLabel))
                    .addGroup(networkPanelLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(networkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(networkPanelLayout.createSequentialGroup()
                                .addGroup(networkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(networkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(serverLabel)
                                        .addComponent(usernameTextField)
                                        .addComponent(serverTextField)
                                        .addComponent(authRequiredCheckBox, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addComponent(usernameLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(networkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(passwordLabel)
                                    .addComponent(portLabel)
                                    .addComponent(portTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(useProxyCheckBox))))
                .addContainerGap(164, Short.MAX_VALUE))
        );
        networkPanelLayout.setVerticalGroup(
            networkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(networkPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(proxySettingsLabel)
                .addGap(5, 5, 5)
                .addComponent(useProxyCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(networkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(serverLabel)
                    .addComponent(portLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(networkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(portTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(serverTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(authRequiredCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(networkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordLabel)
                    .addComponent(usernameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(networkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(60, Short.MAX_VALUE))
        );

        settingsTabbedPane.addTab("Network", networkPanel);

        add(settingsTabbedPane);

        closeButton.setText("Close");

        javax.swing.GroupLayout buttonsPanelLayout = new javax.swing.GroupLayout(buttonsPanel);
        buttonsPanel.setLayout(buttonsPanelLayout);
        buttonsPanelLayout.setHorizontalGroup(
            buttonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buttonsPanelLayout.createSequentialGroup()
                .addContainerGap(484, Short.MAX_VALUE)
                .addComponent(closeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        buttonsPanelLayout.setVerticalGroup(
            buttonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonsPanelLayout.createSequentialGroup()
                .addComponent(closeButton)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        add(buttonsPanel);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel applicationsPanel;
    private javax.swing.JCheckBox authRequiredCheckBox;
    private javax.swing.JCheckBox autodetectApplicationCheckBox;
    private javax.swing.JCheckBox autodetectFileManagerCheckBox;
    private javax.swing.JCheckBox automaticUpdatesCheckBox;
    private javax.swing.JLabel automaticUpdatesLabel;
    private javax.swing.JPanel buttonsPanel;
    private javax.swing.JButton closeButton;
    private javax.swing.JLabel displayBehaviorLabel;
    private javax.swing.JPanel errorReportingPanel;
    private javax.swing.JScrollPane fileTypeApplicationScrollPane;
    private javax.swing.JTable fileTypeApplicationTable;
    private javax.swing.JLabel filesLabel;
    private javax.swing.JLabel foldersLabel;
    private javax.swing.JPanel generalPanel;
    private javax.swing.JPanel networkPanel;
    private javax.swing.JButton openWIthChoiceButton;
    private javax.swing.JLabel openWithLabel;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JLabel portLabel;
    private javax.swing.JFormattedTextField portTextField;
    private javax.swing.JLabel proxySettingsLabel;
    private javax.swing.JCheckBox runOnStartupCheckBox;
    private javax.swing.JLabel serverLabel;
    private javax.swing.JFormattedTextField serverTextField;
    private javax.swing.JTabbedPane settingsTabbedPane;
    private javax.swing.JCheckBox showHiddenFIlesCheckBox;
    private javax.swing.JLabel splitMenusLabel1;
    private javax.swing.JLabel splitMenusLabel2;
    private javax.swing.JFormattedTextField splitMenusPageSizeTextField;
    private javax.swing.JLabel startupLabel;
    private javax.swing.JCheckBox useProxyCheckBox;
    private javax.swing.JLabel usernameLabel;
    private javax.swing.JTextField usernameTextField;
    // End of variables declaration//GEN-END:variables

}
